// Quiz App/Quizzy Vue/src/components/Footer.vue
<template>
    <footer class="sticky-footer">
        <div class="container my-auto">
            <div class="copyright text-center my-auto">
                <span>Copyright © Your Website 2020</span>
            </div>
        </div>
    </footer>
</template>
<script lang="ts">
import { Options, Vue } from "vue-class-component";

@Options({
    components: {},
    props: {},
})
export default class Footer extends Vue {}
</script>

// Football Competition App/Footy React/src/components/Footer.tsx
import React from 'react';

const Footer = () => (
    <footer className="sticky-footer">
        <div className="container my-auto">
            <div className="copyright text-center my-auto">
                <span>Copyright © Footy 2021</span>
            </div>
        </div>
    </footer>
);

export default Footer;
